config/routes.rb
Rails.application.routes.draw do
  resources :recruits do
      resources :recruit_comments, only: [:create, :destroy]
      get 'my_team_index', on: :member
      get 'my_team_show', on: :member
  end

  get '/teams/search', to: 'teams#search'
  resources :teams do
    member do
      get 'management_show'
      get '/user_teams/member'
      get '/user_teams/recruit_member'
    end
    resources :user_teams do
      member do
        patch '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
        put '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
      end
     end
   end

  get '/users/profile_edit', to: 'users#profile_edit'
  get '/users/profile_show', to: 'users#profile_show'
  resources :users
  namespace :admin do
    resources :users
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'users#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController
def create
  @teams = Team.find(params[:team_id])
  @user_team = @teams.user_teams.build(user_id: current_user.id, status: 1)
  if @user_team.save
    flash[:notice] = @teams.name + 'に応募申請成功しました'
    redirect_back(fallback_location: root_path)
end
end

def member
  @team = Team.all
  @user_teams = UserTeam.all
  @team_id = Team.find_by(id: params[:id])
  @user_team = @team_id.user_teams.where(status: 2)
end

def recruit_member
  @team = Team.all
  @user_teams = UserTeam.all
  @team_id = Team.find_by(id: params[:id])
  @user_team = @team_id.user_teams
end

def recruit_member_update
  @user_team = UserTeam.find(params[:team_id])

if @user_team.update(status: 3)
    redirect_to management_show_team_path(), notice: "応募者を拒否しました"
end
end

def update
  @user_team = UserTeam.find(params[:team_id])

if @user_team.update(status: 2)
    redirect_to  management_show_team_path(), notice: "応募者を承認しました"
end
end

private

def team_params
  params.require(:team).permit(:id, :name, :discription, :age, :message,:member, :passion, :Performance,:photo, :enjoy,:photo,:photo_cache,:remove_photo)
end
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
def profile_params
  params.require(:user).permit(:live, :sex, :Birthday)
end
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/views/user_teams/member.html.slim
.team_information_all

  .text-center.team_information_all.mb-5
    h2
      | メンバー一覧
  .recruit_index_table
    table.table.table-hover
      thead.thead-default
       tr
        th= UserTeam.human_attribute_name(:title)
        th= UserTeam.human_attribute_name(:team_id)
        th= UserTeam.human_attribute_name(:Capacity)
        th= UserTeam.human_attribute_name(:body)
        th= UserTeam.human_attribute_name(:created_at)
      tbody
        - @user_team.each do |u|
          tr
           td= u.user_id

      

app/views/user_teams/recruit_member.html.slim
.team_information_all

  .text-center.team_information_all.mb-5
    h2
      | 応募者一覧
  .recruit_index_table
      table.table.table-hover
        thead.thead-default
         tr
          th= UserTeam.human_attribute_name(:title)
          th= UserTeam.human_attribute_name(:team_id)
          th= UserTeam.human_attribute_name(:Capacity)
          th= UserTeam.human_attribute_name(:body)
          th= UserTeam.human_attribute_name(:created_at)
        tbody
          - @user_team.where(status: 1).each do |u|
            tr
             td= u.user_id
             td
               = link_to '承認',team_user_team_path(u.id),:method => :PUT, class: 'btn btn-success mr-3'
             td
               = link_to '承認',user_teams_recruit_member_update_team_user_team_path(u.id),:method => :PUT, class: 'btn btn-success mr-3'