config/routes.rb
Rails.application.routes.draw do
  resources :recruits do
      resources :recruit_comments, only: [:create, :destroy]
      get 'my_team_index', on: :member
      get 'my_team_show', on: :member
  end

  get '/teams/search', to: 'teams#search'
  resources :teams do
    member do
      get 'management_show'
      get '/user_teams/member'
      get '/user_teams/recruit_member'
    end
    resources :user_teams do
      member do
        patch '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
        put '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
      end
     end
   end

  get '/users/profile_edit', to: 'users#profile_edit'
  get '/users/profile_show', to: 'users#profile_show'
  resources :users
  namespace :admin do
    resources :users
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'users#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :teams
  has_many :recruits, dependent: :destroy
  has_many :recruit_comments
  has_many :user_teams
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :_form
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url(@user), notice: "ユーザー「#{@user.name}」を削除しました。"
  end

private

def user_params
  params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
end
def require_admin
  redirect_to root_url unless current_user.admin?
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def index
    @users = User.all
    @teams = Team.all
    render layout:false
  end

  def show
    @user = User.find(params[:id])
    @profile = User.find(session[:user_id])
    @team = @profile.teams
  end


  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def profile_show
    @teams = Team.all
    @profile = User.find(session[:user_id])
    @team = @profile.teams
    render layout: false
  end

  def profile_edit
    @profile = User.find(session[:user_id])

  end

  def create
    @user = User.new(user_params)

    if @user.save
      IdentificationMailer.send_confirm_to_user(@user).deliver
      redirect_to user_url(@user), notice: "ユーザー「#{@user.name}」を作成しました。"
    else
      render :_form
    end
  end


  def update
    @profile = User.find(params[:id])

    if @profile.update(profile_params)
      redirect_to '/users/profile_show', notice: "ユーザーを更新しました。"
    else
      render :profile_edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url(@user), notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def profile_params
    params.require(:user).permit(:live, :sex, :Birthday)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
.nav.justify-content-enabled
  =link_to 'ホーム', users_path, class: 'nav-link'


.new_title
  h1.text-center
    |
      sign up

.form_errors.text-center
  - if @user.errors.present?
      ul#error_explanation
        - @user.errors.full_messages.each do |message|
          li= message

.new_main
  = form_with model: [@user], local: true do |f|

    .user_new_form.form-group
      = f.label :name, '名前'
      = f.text_field :name, class: 'form-control'
    .user_new_form.form-group
      = f.label :email, 'メールアドレス'
      = f.text_field :email, class: 'form-control'
    .user_new_form.form-group
      = f.label :password, 'パスワード'
      = f.text_field :password, class: 'form-control'
    .user_new_form.form-group
      = f.label :password_confirmation, 'パスワード確認'
      = f.text_field :password_confirmation, class: 'form-control'
    .text-center
      = f.submit '登録する', class: 'sign_upbutton btn-lg btn btn-success'

app/views/users/edit.html.slim
h1.text-center
    |
      アカウント編集

.nav.justify-content-enabled
  =link_to '一覧', users_path, class: 'nav-link'

=render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
doctype html
html
  head
    title
      | hukkaru
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'recruits', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light
       .title-main
         = link_to 'フッかる', teams_path, class: 'nav-link'

       .ul.navbar-nav
         - if current_user
           li.nav-item= link_to 'チーム作成', new_team_path, class: 'home nav-link text-white btn-lg btn btn-success'
           li.nav-item= link_to 'チーム検索', teams_search_path, class: 'home nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to '募集掲示板一覧', recruits_path, class: 'recruit_btn nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to 'マイページ', users_profile_show_path, class: 'recruit_btn nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'logout_btn nav-link btn-lg btn-danger text-white'
         - else
          li.nav-item= link_to 'チーム検索', teams_search_path, class: 'log_out_home nav-link text-white btn-lg btn btn-success ml-3'
          li.nav-item= link_to '募集チーム情報', recruits_path, class: 'log_out_home recruit_btn nav-link text-white btn-lg btn-success ml-3'
          li.nav-item= link_to '新規登録', new_user_path, class: 'register-btn btn-lg btn btn-success text-white mr-3'
          li.nav-item= link_to 'ログイン', login_path, class: 'btn-lg btn btn-success text-white'
    .index_all
      .index_title
        h1.text-center.text-white.index_title_main
            |
                フッかる！
        .text-center.index_subtitle.text-white
          p
            | 自分で作ったチームで仲間たちとフットサルしてみよう！
            br
            | 試合相手の検索、試合交渉やチームの作成
            br
            | 近くのチームへの入団を簡単にできるサービスです！
      .container
        .users_index_main
          .hukkaru_description_all
            .discription_title.text-center
              h2 できること


            .hukkaru_description_main.text-center
              h3
                チームに入団する
                  .text-center.team_sub
                    p
                      |ユーザー登録して自分が活動した地域を入力すると
                      br
                      | その地域付近で活動しているチームが出てきたら希望の
                      br
                      | チームに応募しチームから入団が許可されればチーム
                      br
                      |の一員として活動することができるようになります！


            .hukkaru_description_sub.text-center
              h3
                マイチームを作る
                  .text-center
                    p
                      | チーム名や活動場所、チームのプロフィールを登録
                      br
                      | して後は一緒にったかってくれる仲間を募集するだけ！
                      br
                      | 1チーム月額500円で自分のチームを作ることができます！


              h3
                試合相手を見つけるつける
                  .text-center.team_sub
                    p
                      |活動している地域付近で活動しているチームと
                      br
                      | マッチングすることができ、チーム通しで交渉
                      br
                      |していただき試合することができます！


          .team_information_all

            .text-center.team_information_all.mb-5
              h2
                | チーム一覧

            .profile_team_show_all
              .container
               .row
                - @teams.each do |team|
                  =link_to(team_path(team.id),class: 'profile_team_show_table')
                    h5 = team.name
                    .user_team_photo
                      - if team.photo.presence
                        = image_tag team.photo.url
                      - else
                        .photo_none_sub.text-center
                          p 画像は登録されていません
                          = fa_icon ("image 4x")
                      table.table
                        tbody
                         tr
                          th= Team.human_attribute_name(:id)
                          .team_icon
                            td= fa_icon("caret-right 2x")
                          td= team.id
                         tr
                          th= Team.human_attribute_name(:discription)
                          td= fa_icon("caret-right 2x")
                          td= team.discription

app/views/users/new.html.slim
.nav.justify-content-enabled
  =link_to 'ホーム', users_path, class: 'nav-link'


.new_title
  h1.text-center
    |
      sign up

.new_main
  = form_with model: [@user], local: true do |f|

    .user_new_form.form-group
      = f.label :name, '名前'
      = f.text_field :name, class: 'form-control'
    .user_new_form.form-group
      = f.label :email, 'メールアドレス'
      = f.text_field :email, class: 'form-control'
    .user_new_form.form-group
      = f.label :password, 'パスワード'
      = f.text_field :password, class: 'form-control'
    .user_new_form.form-group
      = f.label :password_confirmation, 'パスワード確認'
      = f.text_field :password_confirmation, class: 'form-control'
    .text-center
      = f.submit '登録する', class: 'sign_upbutton btn-lg btn btn-success'

app/views/users/profile_edit.html.slim
.profile_edit_all
  .profile_edit_title.text-center
    h1 プロフィール確認・変更

  .profile_table
    .profile_id
      .profile_label
        h3 = User.human_attribute_name(:id)
      .profile_text
        p = @profile.id

    .profile_name
      .profile_label
        h3 = User.human_attribute_name(:name)
      .profile_text
        p = @profile.name

    .profile_email
      .profile_label
        h3 = User.human_attribute_name(:email)
      .profile_text
        p = @profile.email


  = form_with model: @profile, local: true do |f|
    .new_enjoy_form
      .new_passion.form-group.row
        = f.label :live, 'お住まい', class: 'mr-5', class: 'col-sm-4 text-center'
        = f.select :live, [['北海道'], ['青森'], ['岩手'],['宮城'],['秋田'],['山形'], ['福島'],['茨城'],['栃木'],['群馬'],['埼玉'],['千葉'],['東京'],['神奈川'],['新潟'],['富山'],['石川'],['福井'],['山梨'],['長野'],['岐阜'],['静岡'],['愛知'],['三重'],['滋賀'],['京都'],['大阪'],['兵庫'],['奈良'],['和歌山'],['鳥取'],['島根'],['岡山'],['広島'],['山口'],['徳島'],['香川'],['愛媛'],['高知'],['福岡'],['佐賀'],['長崎'],['熊本'],['大分'],['宮崎'],['鹿児島'],['沖縄']]

    .new_form.form-group.row
      = f.label :sex, '性別' ,class: 'col-sm-4 text-center'
      .profile_sex.text-center
        .profile_sex_male
          = f.radio_button :sex, :"男性"
          = f.label :sex, "男性", {value: :"男性", style: "display: inline-block;"}
        .profile_sex_female
          = f.radio_button :sex, :"女性"
          = f.label :sex, "女性", {value: :"女性", style: "display: inline-block;"}

    .new_form.form-group.row
      = f.label :Birthday, '生年月日', class: 'col-sm-4 text-center'
      = f.text_field :Birthday, class: 'team_text form-control' , id: 'user_Birthday',placeholder:"例) 1999/05/07"

    .profile_button.text-center
      = f.submit 'プロフィール更新', class: 'profile_new_button btn-lg btn btn-success'

app/views/users/profile_new.html.slim
.profile_edit_all
  .profile_edit_title.text-center
    h1 プロフィール確認・変更

  .profile_table
    .profile_id
      .profile_label
        h3 = User.human_attribute_name(:id)
      .profile_text
        p = @profile.id

    .profile_name
      .profile_label
        h3 = User.human_attribute_name(:name)
      .profile_text
        p = @profile.name

    .profile_email
      .profile_label
        h3 = User.human_attribute_name(:email)
      .profile_text
        p = @user.email

  .form_errors.text-center
    - if @user.errors.present?
      ul#error_explanation
        - @user.errors.full_messages.each do |message|
            li= message

  = form_with model: @user, local: true do |f|

    .new_form.form-group.row
      = f.label :leve, 'お住まい' ,class: 'col-sm-4 text-center'
      = f.text_field :leve, class: 'team_text form-control' , id: 'profile_live'

    .new_form.form-group.row
      = f.label :sex, '性別' ,class: 'col-sm-4 text-center'
      = f.radio_button :sex, :male
      = f.label :sex, "男性", {value: :"男性", style: "display: inline-block;"}
      = f.radio_button :sex, :female
      = f.label :sex, "女性", {value: :"女性", style: "display: inline-block;"}

    .new_form.form-group.row
      = f.label :Birthday, '生年月日', class: 'col-sm-4 text-center'
      = f.text_field :age, class: 'team_text form-control' , id: 'profile_Birthday'

    .team_new_button.text-center
      = f.submit 'プロフィール更新', class: 'new_button btn-lg btn btn-success'

app/views/users/profile_show.html.slim
doctype html
html
  head
    title
      | hukkaru
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'recruits', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light
       .title-main
         = link_to 'フッかる', teams_path, class: 'nav-link'

       .ul.navbar-nav
         - if current_user
           li.nav-item= link_to 'チーム作成', new_team_path, class: 'home nav-link text-white btn-lg btn btn-success'
           li.nav-item= link_to 'チーム検索', teams_search_path, class: 'home nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to '募集掲示板一覧', recruits_path, class: 'recruit_btn nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to 'マイページ', users_profile_show_path, class: 'recruit_btn nav-link text-white btn-lg btn btn-success ml-3'
           li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'logout_btn nav-link btn-lg btn-danger text-white'
         - else
          li.nav-item= link_to '新規登録', new_user_path, class: 'register-btn btn-lg btn btn-success text-white mr-3'
          li.nav-item= link_to 'ログイン', login_path, class: 'btn-lg btn btn-success text-white'
    .container
      .my_profile_title.mb-5.mt-4
        h1 マイページ

      .nav.justify-content-center'
        .profile_show_table_all
          .profile_show_table
            table.table.table-hover
             tbody
              tr
               th= 'ユーザーID'
               td= @profile.id
              tr
               th= User.human_attribute_name(:name)
               td= @profile.name
              tr
               th= User.human_attribute_name(:email)
               td= @profile.email
              tr
               th= User.human_attribute_name(:live)
               td= @profile.live
              tr
               th= User.human_attribute_name(:sex)
               td= @profile.sex
              tr
               th= User.human_attribute_name(:Birthday)
               td= @profile.Birthday
          .nav.justify-content-center
            = link_to 'プロフィール編集', '/users/profile_edit', class: 'btn-lg btn btn-success mt-2 w-25'

      .text-center.team_information_all.mb-5
        h2
          | マイチーム一覧

      .profile_team_show_all
        .container
          .row
            - @teams.each do |team|
              =link_to(management_show_team_path(team.id),class: 'profile_team_show_table')
                h5 = team.name
                .user_team_photo
                  - if team.photo.presence
                    = image_tag team.photo.url
                  - else
                    .photo_none_sub.text-center
                      p 画像は登録されていません
                      = fa_icon ("image 4x")
                  table.table
                    tbody
                     tr
                      th= Team.human_attribute_name(:id)
                      td= fa_icon("caret-right 2x")
                      td= team.id
                     tr
                      th= Team.human_attribute_name(:discription)
                      td= fa_icon("caret-right 2x")
                      td= team.discription
  .recruits_description
    .nav.justify-content-center.edit_btn
      = link_to '募集掲示板を作ってみよう！', new_recruit_path, class: 'btn-lg btn btn-success mt-5 w-25'

    .hukkaru_recruit_main.text-center
      h3
        募集掲示板を作成しよう
          .text-center.recruit_new_sub
            p
              = link_to '募集掲示板を作ってみよう', new_recruit_path
              |から募集掲示板を作成して仲間
              br
              | を募集しよう！そのチームで作った募集掲示板は募集掲示
              br
              | 一覧から見れるようになります。内容を変えたい場合は
              br
              | 掲示板を作成したチームの詳細ページから編集できます！


    .hukkaru_recruit_sub.text-center
      h3
        他のチームの募集掲示板を確認しよう
          .text-center
            p
              | チームに参加したい場合は募集掲示板を利用しよう！
              br
              = link_to '募集掲示板一覧', recruits_path
              | から募集しているチームから自分にあった
              br
              | 募集をしているチームを探してコメントしてみよう！


      h3
        掲示板にコメントしよう
          .text-center.team_sub
            p
              |気になる募集を見つけたときはその募集に対してコメント
              br
              | をしてみましょう！チームについての質問やチームの参加
              br
              |願いなどわからないことがあればコメントしよう！

app/views/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-enabled
  =link_to '一覧', users_path, class: 'nav-link'

table.table.table-hover
 tbody
  tr
   th= User.human_attribute_name(:id)
   td= @user.id
  tr
   th= User.human_attribute_name(:name)
   td= @user.name
  tr
   th= User.human_attribute_name(:live)
   td= @profile.live
  tr
   th= User.human_attribute_name(:sex)
   td= @profile.sex
  tr
   th= User.human_attribute_name(:Birthday)
   td= @profile.Birthday
  tr
   th= User.human_attribute_name(:created_at)
   td= @user.created_at