config/routes.rb
Rails.application.routes.draw do
  resources :recruits do
      resources :recruit_comments, only: [:create, :destroy]
      get 'my_team_index', on: :member
      get 'my_team_show', on: :member
  end

  get '/teams/search', to: 'teams#search'
  resources :teams do
    member do
      get 'management_show'
      get '/user_teams/member'
      get '/user_teams/recruit_member'
    end
    resources :user_teams do
      member do
        patch '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
        put '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
      end
     end
   end

  get '/users/profile_edit', to: 'users#profile_edit'
  get '/users/profile_show', to: 'users#profile_show'
  resources :users
  namespace :admin do
    resources :users
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'users#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/recruit.rb
class Recruit < ApplicationRecord
  validates :title, presence: true
  validates :Capacity, presence: true
  validates :body, presence: true

  has_many :recruit_comments
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  skip_before_action :login_required, only: [:index,:show]

  def index
    @teams = Team.all
    @recruits = Recruit.all
  end

  def my_team_index
    @recruits = Recruit.all
    @team_id = Team.find_by(id: params[:id])
    @recruit = @team_id.recruits
  end
  def new
    @teams = Team.all
    @recruit = Recruit.new
  end

  def show
    @recruit = Recruit.find(params[:id])
    @recruit_comments = @recruit.recruit_comments
    @recruit_comment = @recruit.recruit_comments.new
    @user = User.find_by(id: @recruit_comment.user_id)
    @users = User.find(params[:id])
  end

  def my_team_show
    @recruits = Recruit.all
    @recruit = Recruit.find(params[:id])
  end

  def create
    @recruit = Recruit.new(recruits_params)

    if @recruit.save
      redirect_to my_team_show_recruit_path(@recruit), notice: "「#{@recruit.title}」を募集掲示板に登録しました"
    else
      render :new
    end
  end


  def edit
    @recruit = Recruit.find(params[:id])
  end

  def update
    @recruit = Recruit.find(params[:id])

    if @recruit.update(recruits_params)
      redirect_to my_team_show_recruit_url(@recruit), notice: "ユーザーを更新しました。"
    else
      render :recruit_edit
    end
  end


  def destroy
    @recruit = Recruit.find(params[:id])
    @recruit.destroy
    redirect_to users_profile_show_url, notice: "ユーザー「#{@recruit.title}」を削除しました。"
  end


  private

  def team_params
    params.require(:team).permit(:id, :name, :discription, :age, :message, :passion, :Performance, :enjoy)
  end
  def recruits_params
    params.require(:recruit).permit(:title, :body, :photo, :Capacity, :team_id)
  end
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/recruits/edit.html.slim
.team_edit_all
  .nav.justify-content-start
    =link_to 'マイチーム', teams_path, class: 'nav-link'

  .text-center
    .team_title
      h1　チームプロフィール変更

  .form_errors.text-center
    - if @recruit.errors.present?
      ul#error_explanation
        - @recruit.errors.full_messages.each do |message|
            li= message

  = form_with model: @recruit, local: true do |f|
    .new_form.form-group.row
      = f.label :title, '募集概要' ,class: 'col-sm-4 text-center'
      = f.text_field :title, class: 'team_text form-control' , id: 'recruit_title'

    .new_form.form-group.row
      = f.label :Capacity, '募集人数', class: 'col-sm-4 text-center'
      = f.text_field :Capacity, class: 'team_text form-control' , id: 'recruit_Capacity'

    .form_message.form-group.row
      = f.label :body, 'チームから一言',class: 'col-sm-4 text-center'
      = f.text_area :body, rows: 5, class: 'team_new_message form-control', id: 'recruit_body'

    .new_recruit_form
      .new_recruit.form-group.row
        = f.label :team_name, '募集したいチーム名', class: 'mr-5', class: 'col-sm-4 text-center'
        = f.collection_select :team_id, Team.all, :id , :name, :prompt => true


    .recruit_new_button.text-center
      = f.submit '募集掲示板作成', class: 'recruit_button btn-lg btn btn-success'

app/views/recruits/index.html.slim
.team_information_all

  .text-center.team_information_all.mb-5
    h2
      | 募集情報一覧
  .recruit_index_table
    table.table.table-hover
      thead.thead-default
       tr
        th= Recruit.human_attribute_name(:title)
        th= Recruit.human_attribute_name(:team_name)
        th= Recruit.human_attribute_name(:Capacity)
        th= Recruit.human_attribute_name(:body)
        th= Recruit.human_attribute_name(:created_at)
      tbody
        - @recruits.each do |recruit|
         tr
          td= link_to recruit.title, recruit
          td= recruit.team_id
          td= recruit.Capacity
          td= recruit.body
          td= recruit.created_at

app/views/recruits/my_team_index.html.slim
.team_information_all

  .text-center.team_information_all.mb-5
    h2
      | 募集情報一覧

  table.table.table-hover
   thead.thead-default
    tr
      th= Recruit.human_attribute_name(:id)
      th= Recruit.human_attribute_name(:title)
      th= Recruit.human_attribute_name(:team_id)
      th= Recruit.human_attribute_name(:Capacity)
      th= Recruit.human_attribute_name(:created_at)
   tbody
    - @recruit.each do |recruit|
      =link_to (my_team_show_recruit_path(recruit.id))
        tr
         td= recruit.id
         td= link_to recruit.title, my_team_show_recruit_path(recruit.id)
         td= recruit.team_id
         td= recruit.Capacity
         td= recruit.created_at

app/views/recruits/my_team_show.html.slim
.index_all

.recruit_information_all

  .nav.justify-content-enabled
    =link_to '募集情報一覧', recruits_path, class: 'nav-link'

  .text-center.team_information_all.mb-5
    h2
      | 募集内容確認

table.table.table-hover
  tbody
  tr
    th= Recruit.human_attribute_name(:id)
    td= @recruit.id
  tr
    th= Recruit.human_attribute_name(:title)
    td= @recruit.title
  tr
    th= Recruit.human_attribute_name(:team_id)
    td= @recruit.team_id
  tr
    th= Recruit.human_attribute_name(:Capacity)
    td= @recruit.Capacity

  tr
    th= Recruit.human_attribute_name(:body)
    td= @recruit.body

  tr
    th= Recruit.human_attribute_name(:created_at)
    td= @recruit.created_at

.nav.justify-content-center.edit_btn
  = link_to '編集する', edit_recruit_path, class: 'btn-lg btn btn-success mt-5'
  = link_to '削除する', "/recruits/#{@recruit.id}", method: :delete, data: { confirm: "タスク「#{@recruit.title}」を削除します。よろしいですか？" }, class: 'btn-lg btn btn-danger mt-5 ml-4'

app/views/recruits/new.html.slim
.nav.justify-content-start
  =link_to 'ホーム', teams_path, class: 'nav-link'

.text-center
  .recruit_title
    h1　募集内容作成！

.recruit_sub.text-center
  p
    | 募集掲示板を作って
    br
    | 一緒にフットサルを一緒にやってくれる人を募集しよう！


.form_errors.text-center
  - if @recruit.errors.present?
    ul#error_explanation
      - @recruit.errors.full_messages.each do |message|
          li= message

= form_with model: @recruit, local: true do |f|

  .new_form.form-group.row
    = f.label :title, '募集概要' ,class: 'col-sm-4 text-center'
    = f.text_field :title, class: 'team_text form-control' , id: 'recruit_title'

  .new_form.form-group.row
    = f.label :Capacity, '募集人数', class: 'col-sm-4 text-center'
    = f.text_field :Capacity, class: 'team_text form-control' , id: 'recruit_Capacity'

  .form_message.form-group.row
    = f.label :body, 'チームから一言',class: 'col-sm-4 text-center'
    = f.text_area :body, rows: 5, class: 'team_new_message form-control', id: 'recruit_body'

  .new_recruit_form
    .new_recruit.form-group.row
      = f.label :team_name, '募集したいチーム名', class: 'mr-5', class: 'col-sm-4 text-center'
      = f.collection_select :team_id, Team.all, :id , :name, :prompt => true


  .recruit_new_button.text-center
    = f.submit '募集掲示板作成', class: 'recruit_button btn-lg btn btn-success'

app/views/recruits/show.html.slim
.index_all

.recruit_information_all

  .nav.justify-content-enabled
    =link_to '募集情報一覧', recruits_path, class: 'nav-link'

  .text-center.team_information_all.mb-5
    h2
      | 募集内容確認

.recruit_show_table
  table.table.table-hover
   tbody
    tr
     th= Recruit.human_attribute_name(:title)
     td= @recruit.title
    tr
     th= Recruit.human_attribute_name(:team_id)
     td= @recruit.team_id
    tr
     th= Recruit.human_attribute_name(:Capacity)
     td= @recruit.Capacity

    tr
     th= Recruit.human_attribute_name(:body)
     td= @recruit.body

    tr
     th= Recruit.human_attribute_name(:created_at)
     td= @recruit.created_at


.comment-wrapper.mb-10
  .mt-5.comment_title
    p コメント一覧
    .comments_all
      - @recruit_comments.each do |c|
        - unless c.user.blank?
          table.table.table-hover
           tbody
            tr
             th= link_to c.user.name, user_path(@users)
             td= c.body
  - if current_user
    = form_with(model: [@recruit, @recruit_comment], local: true) do |f|
      = f.text_area :body, class: "form-control", rows: 5
      = button_tag type: "submit", class: "comment_btn btn btn-success float-right mt-1"
        = fa_icon("comment 2x")
        p コメントする