config/routes.rb
Rails.application.routes.draw do
  resources :recruits do
      resources :recruit_comments, only: [:create, :destroy]
      get 'my_team_index', on: :member
      get 'my_team_show', on: :member
  end

  get '/teams/search', to: 'teams#search'
  resources :teams do
    member do
      get 'management_show'
      get '/user_teams/member'
      get '/user_teams/recruit_member'
    end
    resources :user_teams do
      member do
        patch '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
        put '/user_teams/recruit_member_update', to: 'user_teams#recruit_member_update'
      end
     end
   end

  get '/users/profile_edit', to: 'users#profile_edit'
  get '/users/profile_show', to: 'users#profile_show'
  resources :users
  namespace :admin do
    resources :users
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'users#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :teams
  has_many :recruits, dependent: :destroy
  has_many :recruit_comments
  has_many :user_teams
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :_form
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url(@user), notice: "ユーザー「#{@user.name}」を削除しました。"
  end

private

def user_params
  params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
end
def require_admin
  redirect_to root_url unless current_user.admin?
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def index
    @users = User.all
    @teams = Team.all
    render layout:false
  end

  def show
    @user = User.find(params[:id])
    @profile = User.find(session[:user_id])
    @team = @profile.teams
  end


  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def profile_show
    @teams = Team.all
    @profile = User.find(session[:user_id])
    @team = @profile.teams
    render layout: false
  end

  def profile_edit
    @profile = User.find(session[:user_id])

  end

  def create
    @user = User.new(user_params)

    if @user.save
      IdentificationMailer.send_confirm_to_user(@user).deliver
      redirect_to user_url(@user), notice: "ユーザー「#{@user.name}」を作成しました。"
    else
      render :_form
    end
  end


  def update
    @profile = User.find(params[:id])

    if @profile.update(profile_params)
      redirect_to '/users/profile_show', notice: "ユーザーを更新しました。"
    else
      render :profile_edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url(@user), notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def profile_params
    params.require(:user).permit(:live, :sex, :Birthday)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
- if @user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.text_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.text_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-success text-center'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-enabled
  =link_to '一覧', admin_users_path, class: 'nav-link'

=render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1.text-center
    |
       ユーザー一覧

=link_to '新規登録', new_admin_user_path, class: 'btn btn-success'

.mb-3
table.table.table-hover
  thead.thead-default
   tr
     th= User.human_attribute_name(:name)
     th= User.human_attribute_name(:email)
     th
  tbody
    - @users.each do |user|
      tr
       td= link_to user.name, [:admin, user]
       td= user.email
       td
        = link_to '編集', edit_admin_user_path(user), class: 'btn btn-success mr-3'
        = link_to '削除', [:admin, user], method: :delete, data: { confirm: "タスク「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1.text-center
  |
    sign in

.nav.justify-content-enabled
  =link_to '一覧', admin_users_path, class: 'nav-link'


= form_with model: [:admin, @user], local: true do |f|
  .form-group.
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password
    = f.text_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation
    = f.text_field :password_confirmation, class: 'form-control'
  .text-center
    = f.submit '登録する', class: 'btn btn-success'

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-enabled
  =link_to '一覧', admin_users_path, class: 'nav-link'

table.table.table-hover
 tbody
  tr
   th= User.human_attribute_name(:id)
   td= @user.id
  tr
   th= User.human_attribute_name(:name)
   td= @user.name
  tr
   th= User.human_attribute_name(:email)
   td= @user.email
  tr
   th= User.human_attribute_name(:admin)
   td= @user.admin? ? 'あり':'なし'
  tr
   th= User.human_attribute_name(:created_at)
   td= @user.created_at
  tr
   th= User.human_attribute_name(:updated_at)
   td= @user.updated_at
        = link_to '編集', edit_admin_user_path(user), class: 'btn btn-success mr-3'
        = link_to '削除', [:admin, user], method: :delete, data: { confirm: "タスク「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'